#!name= قناص روابط البث العربي
#!desc= يقتنص روابط البث المباشر mp4 و m3u8 من مواقع أكوام وفاصل نت تلقائياً.
#!author= Abdulluh.X
#!homepage= https://t.me/plex_arab

[rewrite_local]
^https?:\/\/.*?\.(mp4|m3u8|mov).* url script-request-header ضع_رابط_الـRaw_لملف_الجافا_سكربت_هنا
^https?:\/\/.*?\/(video|stream|playlist|hls).* url script-request-header ضع_رابط_الـRaw_لملف_الجافا_سكربت_هنا

[mitm]
hostname = *.akoam.*, *.fasel*, *.video.*, *.stream.*, *.fushaar.*
